/*******************************************************************************
 * Copyright (C) 2021 Ghent University - imec, IDLab
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *   Tim Verbelen
 *   Steven Bohez
 *   Elias De Coninck
 ******************************************************************************/
package franka_gripper;

public interface GraspAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "franka_gripper/GraspAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nGraspActionGoal action_goal\nGraspActionResult action_result\nGraspActionFeedback action_feedback\n";
  franka_gripper.GraspActionGoal getActionGoal();
  void setActionGoal(franka_gripper.GraspActionGoal value);
  franka_gripper.GraspActionResult getActionResult();
  void setActionResult(franka_gripper.GraspActionResult value);
  franka_gripper.GraspActionFeedback getActionFeedback();
  void setActionFeedback(franka_gripper.GraspActionFeedback value);
}
