/*******************************************************************************
 * Copyright (C) 2021 Ghent University - imec, IDLab
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *   Tim Verbelen
 *   Steven Bohez
 *   Elias De Coninck
 ******************************************************************************/
package franka_gripper;

public interface HomingAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "franka_gripper/HomingAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHomingActionGoal action_goal\nHomingActionResult action_result\nHomingActionFeedback action_feedback\n";
  franka_gripper.HomingActionGoal getActionGoal();
  void setActionGoal(franka_gripper.HomingActionGoal value);
  franka_gripper.HomingActionResult getActionResult();
  void setActionResult(franka_gripper.HomingActionResult value);
  franka_gripper.HomingActionFeedback getActionFeedback();
  void setActionFeedback(franka_gripper.HomingActionFeedback value);
}
