/*******************************************************************************
 * Copyright (C) 2021 Ghent University - imec, IDLab
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *   Tim Verbelen
 *   Steven Bohez
 *   Elias De Coninck
 ******************************************************************************/
package franka_gripper;

public interface MoveAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "franka_gripper/MoveAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nMoveActionGoal action_goal\nMoveActionResult action_result\nMoveActionFeedback action_feedback\n";
  franka_gripper.MoveActionGoal getActionGoal();
  void setActionGoal(franka_gripper.MoveActionGoal value);
  franka_gripper.MoveActionResult getActionResult();
  void setActionResult(franka_gripper.MoveActionResult value);
  franka_gripper.MoveActionFeedback getActionFeedback();
  void setActionFeedback(franka_gripper.MoveActionFeedback value);
}
