/*******************************************************************************
 * Copyright (C) 2021 Ghent University - imec, IDLab
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *   Tim Verbelen
 *   Steven Bohez
 *   Elias De Coninck
 ******************************************************************************/
package franka_gripper;

public interface StopAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "franka_gripper/StopAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nStopActionGoal action_goal\nStopActionResult action_result\nStopActionFeedback action_feedback\n";
  franka_gripper.StopActionGoal getActionGoal();
  void setActionGoal(franka_gripper.StopActionGoal value);
  franka_gripper.StopActionResult getActionResult();
  void setActionResult(franka_gripper.StopActionResult value);
  franka_gripper.StopActionFeedback getActionFeedback();
  void setActionFeedback(franka_gripper.StopActionFeedback value);
}
