/*******************************************************************************
 * Copyright (C) 2021 Ghent University - imec, IDLab
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *   Tim Verbelen
 *   Steven Bohez
 *   Elias De Coninck
 ******************************************************************************/
package franka_control;

public interface ErrorRecoveryAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "franka_control/ErrorRecoveryAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nErrorRecoveryActionGoal action_goal\nErrorRecoveryActionResult action_result\nErrorRecoveryActionFeedback action_feedback\n";
  franka_control.ErrorRecoveryActionGoal getActionGoal();
  void setActionGoal(franka_control.ErrorRecoveryActionGoal value);
  franka_control.ErrorRecoveryActionResult getActionResult();
  void setActionResult(franka_control.ErrorRecoveryActionResult value);
  franka_control.ErrorRecoveryActionFeedback getActionFeedback();
  void setActionFeedback(franka_control.ErrorRecoveryActionFeedback value);
}
