/*******************************************************************************
 * Copyright (C) 2021 Ghent University - imec, IDLab
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *   Tim Verbelen
 *   Steven Bohez
 *   Elias De Coninck
 ******************************************************************************/
package moveit_msgs;

public interface PlaceAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "moveit_msgs/PlaceAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nPlaceActionGoal action_goal\nPlaceActionResult action_result\nPlaceActionFeedback action_feedback\n";
  moveit_msgs.PlaceActionGoal getActionGoal();
  void setActionGoal(moveit_msgs.PlaceActionGoal value);
  moveit_msgs.PlaceActionResult getActionResult();
  void setActionResult(moveit_msgs.PlaceActionResult value);
  moveit_msgs.PlaceActionFeedback getActionFeedback();
  void setActionFeedback(moveit_msgs.PlaceActionFeedback value);
}
