/*******************************************************************************
 * Copyright (C) 2021 Ghent University - imec, IDLab
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *   Tim Verbelen
 *   Steven Bohez
 *   Elias De Coninck
 ******************************************************************************/
package control_msgs;

public interface PointHeadAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "control_msgs/PointHeadAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nPointHeadActionGoal action_goal\nPointHeadActionResult action_result\nPointHeadActionFeedback action_feedback\n";
  control_msgs.PointHeadActionGoal getActionGoal();
  void setActionGoal(control_msgs.PointHeadActionGoal value);
  control_msgs.PointHeadActionResult getActionResult();
  void setActionResult(control_msgs.PointHeadActionResult value);
  control_msgs.PointHeadActionFeedback getActionFeedback();
  void setActionFeedback(control_msgs.PointHeadActionFeedback value);
}
