/*******************************************************************************
 * Copyright (C) 2021 Ghent University - imec, IDLab
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *   Tim Verbelen
 *   Steven Bohez
 *   Elias De Coninck
 ******************************************************************************/
package control_msgs;

public interface PointHeadGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "control_msgs/PointHeadGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\ngeometry_msgs/PointStamped target\ngeometry_msgs/Vector3 pointing_axis\nstring pointing_frame\nduration min_duration\nfloat64 max_velocity\n";
  geometry_msgs.PointStamped getTarget();
  void setTarget(geometry_msgs.PointStamped value);
  geometry_msgs.Vector3 getPointingAxis();
  void setPointingAxis(geometry_msgs.Vector3 value);
  java.lang.String getPointingFrame();
  void setPointingFrame(java.lang.String value);
  org.ros.message.Duration getMinDuration();
  void setMinDuration(org.ros.message.Duration value);
  double getMaxVelocity();
  void setMaxVelocity(double value);
}
