/*******************************************************************************
 * Copyright (C) 2021 Ghent University - imec, IDLab
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *   Tim Verbelen
 *   Steven Bohez
 *   Elias De Coninck
 ******************************************************************************/
package control_msgs;

public interface SingleJointPositionAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "control_msgs/SingleJointPositionAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nSingleJointPositionActionGoal action_goal\nSingleJointPositionActionResult action_result\nSingleJointPositionActionFeedback action_feedback\n";
  control_msgs.SingleJointPositionActionGoal getActionGoal();
  void setActionGoal(control_msgs.SingleJointPositionActionGoal value);
  control_msgs.SingleJointPositionActionResult getActionResult();
  void setActionResult(control_msgs.SingleJointPositionActionResult value);
  control_msgs.SingleJointPositionActionFeedback getActionFeedback();
  void setActionFeedback(control_msgs.SingleJointPositionActionFeedback value);
}
