/*******************************************************************************
 * Copyright (C) 2021 Ghent University - imec, IDLab
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *   Tim Verbelen
 *   Steven Bohez
 *   Elias De Coninck
 ******************************************************************************/
package object_recognition_msgs;

public interface ObjectRecognitionAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "object_recognition_msgs/ObjectRecognitionAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nObjectRecognitionActionGoal action_goal\nObjectRecognitionActionResult action_result\nObjectRecognitionActionFeedback action_feedback\n";
  object_recognition_msgs.ObjectRecognitionActionGoal getActionGoal();
  void setActionGoal(object_recognition_msgs.ObjectRecognitionActionGoal value);
  object_recognition_msgs.ObjectRecognitionActionResult getActionResult();
  void setActionResult(object_recognition_msgs.ObjectRecognitionActionResult value);
  object_recognition_msgs.ObjectRecognitionActionFeedback getActionFeedback();
  void setActionFeedback(object_recognition_msgs.ObjectRecognitionActionFeedback value);
}
